"""Serialize policy rules to nullfield NullfieldPolicy YAML."""

from __future__ import annotations

from typing import Any

from mcpnuke.policy.rules import PolicyRule


def serialize_policy(
    rules: list[PolicyRule],
    name: str = "mcpnuke-recommended",
    namespace: str = "",
    selector_labels: dict[str, str] | None = None,
    metadata_labels: dict[str, str] | None = None,
) -> str:
    """Convert PolicyRule list to a nullfield-compatible YAML string.

    Parameters
    ----------
    rules:
        Policy rules produced by :func:`mcpnuke.policy.generator.generate_policy`.
    name:
        ``metadata.name`` of the resulting NullfieldPolicy.
    namespace:
        ``metadata.namespace``. Empty string means cluster-scoped or
        namespace-at-apply-time.
    selector_labels:
        ``spec.selector.matchLabels``. When ``None`` or empty, the selector
        matches every pod — almost always too broad for a real cluster.
        Callers integrating with K8s should always set this (e.g.
        ``{"app": "brain-gateway"}``).
    metadata_labels:
        ``metadata.labels``. Useful for tagging the policy with lane /
        transport metadata so dashboards can group it.
    """
    spec_selector: dict[str, Any] = {
        "matchLabels": dict(selector_labels) if selector_labels else {}
    }
    metadata: dict[str, Any] = {"name": name}
    if namespace:
        metadata["namespace"] = namespace
    if metadata_labels:
        metadata["labels"] = dict(metadata_labels)

    policy: dict[str, Any] = {
        "apiVersion": "nullfield.io/v1alpha1",
        "kind": "NullfieldPolicy",
        "metadata": metadata,
        "spec": {
            "selector": spec_selector,
            "rules": [],
        },
    }

    for rule in rules:
        entry: dict[str, Any] = {
            "action": rule.action,
            "mcpMethod": "tools/call",
            "toolNames": rule.tool_names,
            "reason": rule.reason,
        }

        if rule.hold:
            entry["hold"] = rule.hold
        if rule.scope:
            entry["scope"] = rule.scope
        if rule.budget:
            entry["budget"] = rule.budget

        policy["spec"]["rules"].append(entry)

    return _manual_yaml(policy)


def _manual_yaml(policy: dict) -> str:
    """Fallback YAML serializer when PyYAML is not available."""
    import json

    lines = ["# Generated by mcpnuke --generate-policy"]
    lines.append(f"apiVersion: {policy['apiVersion']}")
    lines.append(f"kind: {policy['kind']}")
    lines.append("metadata:")
    lines.append(f"  name: {policy['metadata']['name']}")
    if "namespace" in policy["metadata"]:
        lines.append(f"  namespace: {policy['metadata']['namespace']}")
    if "labels" in policy["metadata"]:
        lines.append("  labels:")
        for k, v in policy["metadata"]["labels"].items():
            lines.append(f"    {json.dumps(k)}: {json.dumps(v)}")
    lines.append("spec:")
    lines.append("  selector:")
    selector_labels = policy["spec"]["selector"]["matchLabels"]
    if selector_labels:
        lines.append("    matchLabels:")
        for k, v in selector_labels.items():
            lines.append(f"      {json.dumps(k)}: {json.dumps(v)}")
    else:
        lines.append("    matchLabels: {}")
    rules = policy["spec"]["rules"]
    lines.append("  rules:" if rules else "  rules: []")

    for rule in rules:
        lines.append(f"    - action: {rule['action']}")
        lines.append(f"      mcpMethod: {rule['mcpMethod']}")
        tools = json.dumps(rule["toolNames"])
        lines.append(f"      toolNames: {tools}")
        lines.append(f"      reason: {json.dumps(rule['reason'])}")
        for key in ("hold", "scope", "budget"):
            if key in rule:
                lines.append(f"      {key}:")
                for k, v in rule[key].items():
                    if isinstance(v, dict):
                        lines.append(f"        {k}:")
                        for kk, vv in v.items():
                            lines.append(f"          {kk}: {json.dumps(vv)}")
                    else:
                        lines.append(f"        {k}: {json.dumps(v)}")

    return "\n".join(lines) + "\n"
