apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpredator
  namespace: mcpredator
  labels:
    app.kubernetes.io/name: mcpredator
    app.kubernetes.io/part-of: agentsmith
automountServiceAccountToken: true
